### PR TITLE
Add "Save settings" button to ease testing settings

### PR DESCRIPTION
**Pull request by pixdoet**
abc

### CODE REVIEW

**Comment by pixdoet** [comment]
daadsdfsdafcasdc asfcadf dfc asdc ag xghsnfhhgvsdv sdfvc

**Comment by pixdoet** [comment]
Im pretty sure I got this correct this time, last time i forgot to declare `e0`.

**Comment by 7kt-swe** [comment]
> Im pretty sure I got this correct this time, last time i forgot to declare `e0`.

It's hard for me to go through the actual code that you've implemented/changed when you run the document in a cleanup/beautifyer which edit almost the whole document with changes

**Review by 7kt-swe — CHANGES_REQUESTED** [review]
> Im pretty sure I got this correct this time, last time i forgot to declare `e0`.

It's hard for me to go through the actual code that you've implemented/changed when you run the document in a cleanup/beautifyer which make edits to the whole document more or less

**Comment by pixdoet** [comment]
k uhh lemme submit a new pr

**Pull request closed without merging**
